services:
  postgres:
    image: postgres:13.4
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./initdb/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
  redis:
    image: redis:6.2.5
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
