postgres:
  image: postgres:13.4
  ports:
    - ${PG_PORT}:5432
  volumes:
    - ./data/postgres:/var/lib/postgresql/data
    - ./initdb/postgres:/docker-entrypoint-initdb.d
  environment:
    POSTGRES_USER: ${PG_USER}
    POSTGRES_PASSWORD: ${PG_PASSWORD}
    POSTGRES_DB: ${PG_DB}
  